# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
  #     desired widget in your `content/home/` folder.
  #   The weight parameter defines the order that the links will appear in.

main:
  - name: Blog
    url: /#news
    weight: 10
  - name: Projects
    url: projects/
    weight: 11
  - name: About Me
    url: /
    weight: 20
  # - name: Skills
  #   url: /#skills
  #   weight: 11
  # - name: Experience
  #   url: experience/
  #   weight: 12
  # - name: Publication
  #   url: /#papers
  #   weight: 13
  # - name: Awards
  #   url: /#talks
  #   weight: 14
  # - name: Teaching
  #   url: teaching/
  #   weight: 40
